config/routes.rb
Rails.application.routes.draw do
	get 'upload'		=> 'uploads#new'
	get 'dashboard' => 'uploads#index'
	
	resources :uploads do
		get 'pay'
		post 'payment_token'
	end

end

app/models/upload.rb
class Upload < ActiveRecord::Base
	#attr_accessor :current_status
	
	validates(:name, presence: true, length: {maximum: 30})
	validates(:description, presence: true, length: {maximum: 140})
	validates(:price, presence: true, length: {maximum: 5})

	has_attached_file :file 

	validates_attachment_content_type :file, content_type: /\Aapplication\/.*\Z/
	#validates_attachment_content_type :file, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
	
	skip_before_filter :verify_authenticity_token, :only => [:payment_token]
	 
 	def index
		@uploads = Upload.all
	end
  
	def show
		@upload = Upload.find(params[:id])
	end
	
	def new
  	@upload = Upload.new
	end

	def create
		#model URL is saved by paperclip check Upload.file.url
		@upload = Upload.new(upload_params)
		@upload.current_status = "uploaded"
		if @upload.save
			flash[:success] = "upload sucessful"
			redirect_to dashboard_path
		else
			render 'new'
		end
	end
	
	def pay
		@upload = Upload.find(params[:upload_id]) 
	end

	def payment_token
		@upload = Upload.find(params[:upload_id])
		Stripe.api_key = "sk_test_d5xSfWEXkyfkgMR9b9RUZNVk"

		# Get the credit card details submitted by the form
		token = params[:stripeToken]

		# Create the charge on Stripe's servers - this will charge the user's card
		begin
		charge = Stripe::Charge.create(
				:amount => (@upload.price*100).to_i, # amount in cents, again
				:currency => "usd",
				:source => token,
				:description => @upload.name
				)
		rescue Stripe::CardError => e
		# The card has been declined
		end
		@upload.current_status = "Payed"
		@upload.save
		render 'pay'
	end

	private
		
	def upload_params
		params.require(:upload).permit(:name, :description, :price, :file)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Lani Mockup App"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<nav>
	 	 <ul class="nav navbar-nav navbar-right">
	  	 <li><%= link_to "Upload",     upload_path 		%></li>
		   <li><%= link_to "Dashboard",  dashboard_path %></li>
	   </ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/uploads/_error_messages.html.erb
<% if @upload.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			There are <%= pluralize(@upload.errors.count, "error") %>.
		</div>
		<ul>
			<% @upload.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/uploads/index.html.erb
<% provide(:title, 'Dashboard') %>
<h1>Dashboard</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
			<th>Price</th>
			<th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= upload.name %></td>
        <td><%= upload.description %></td>
				<td><%= upload.price %></td>
				<td><%= upload.current_status %></td>
				<td>
					<% if upload.current_status != "Payed" %>
						<%= link_to "Pay here", upload_pay_path(upload), class: "btn btn-xs btn-primary" %>
					<% end %>
				</td>
				</form>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/uploads/new.html.erb
<% provide(:title, 'Upload') %>
<h1>Upload Files</h1>
	
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @upload, html: {multipart: true} do |f| %>
			<%= render 'uploads/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :description %>
			<%= f.text_field :description, class: 'form-control' %>

			<%= f.label :price %>
			<%= f.number_field :price, step: 'any', class: 'form-control' %>

			<%= f.label :file %>
			<%= f.file_field :file, class: 'form-control'  %>

			<%= f.submit "Submit file", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/uploads/pay.html.erb
<% provide(:title, 'Pay') %>
<h1>Pay</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
			<th>Price</th>
			<th>Status</th>
    </tr>
  </thead>

  <tbody>
			<tr>
        <td><%= @upload.name %></td>
        <td><%= @upload.description %></td>
				<td><%= @upload.price %></td>
				<td><%= @upload.current_status %></td>
				<td><form action="<%= upload_payment_token_path(@upload) %>" method="POST">
						<input type='hidden' name='upload_id' value='<%= @upload.id %>'>
				  	<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
							data-key="pk_test_gsT2ktTl82MKmR6hLPl5qcaB"
							data-amount= "<%= (@upload.price*100).to_s%>"
							data-name="Print <%= @upload.name %>"
							data-description="<%= @upload.description %>"
							data-image="/128x128.png"
							data-locale="auto">
					 	</script>
					</form>
				</td>
				</form>
      </tr>
  </tbody>
</table>

app/views/uploads/show.html.erb
<%= @upload.name %>, <%= @upload.price%>